image:
  tag: 8.4.6-debian-10-r7
admin:
  password: admin
service:
  type: NodePort
persistence:
  enabled: false
metrics:
  enabled: true
dashboardsProvider:
  enabled: true
dashboardsConfigMaps:
  - configMapName: movies-api-dashboard
    fileName: movies-api-dashboard.json
datasources:
  secretName: grafana-datasource-secret
