image:
  tag: 8.0.32-debian-11-r6
auth:
  rootPassword: root-password
  username: keycloak
  password: keycloak
  database: keycloak
primary:
  persistence:
    enabled: false
secondary:
  replicaCount: 0